# Generated by Django 5.1.4 on 2025-01-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherquery',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
